In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)

In [3]:
business_ids = [f"B{i:03d}" for i in range(1, 501)]
business_ids[:5], business_ids[-5:]

(['B001', 'B002', 'B003', 'B004', 'B005'],
 ['B496', 'B497', 'B498', 'B499', 'B500'])

In [4]:
owner_ids = [f"O{i:03d}" for i in range(1, 501)]
owner_ids[:5], owner_ids[-5:]

(['O001', 'O002', 'O003', 'O004', 'O005'],
 ['O496', 'O497', 'O498', 'O499', 'O500'])

In [5]:
business_types = (
    ["Retail Shop"] * 100 +
    ["Food Vendor"] * 80 +
    ["Transport Worker"] * 60 +
    ["Artisan"] * 50 +
    ["Freelancer"] * 50 +
    ["Small Producer"] * 60 +
    ["Home Business"] * 50 +
    ["Micro Service Business"] * 50
)

len(business_types)

500

In [6]:
business_types = np.random.permutation(business_types)

business_types[:10]

array(['Small Producer', 'Retail Shop', 'Small Producer', 'Food Vendor',
       'Food Vendor', 'Small Producer', 'Small Producer', 'Food Vendor',
       'Retail Shop', 'Micro Service Business'], dtype='<U22')

In [7]:
pd.Series(business_types).value_counts()

Retail Shop               100
Food Vendor                80
Small Producer             60
Transport Worker           60
Micro Service Business     50
Home Business              50
Freelancer                 50
Artisan                    50
Name: count, dtype: int64

In [8]:
business_df = pd.DataFrame({
    "business_id": business_ids,
    "owner_id": owner_ids,
    "business_type": business_types
})

business_df.head()

  business_id owner_id   business_type
0        B001     O001  Small Producer
1        B002     O002     Retail Shop
2        B003     O003  Small Producer
3        B004     O004     Food Vendor
4        B005     O005     Food Vendor

In [9]:
environment_types = (
    ["Urban"] * 175 +
    ["Semi-Urban"] * 125 +
    ["Rural"] * 125 +
    ["Peri-Urban"] * 75
)

environment_types = np.random.permutation(environment_types)

pd.Series(environment_types).value_counts()

Urban         175
Rural         125
Semi-Urban    125
Peri-Urban     75
Name: count, dtype: int64

In [10]:
business_df["environment_type"] = environment_types

business_df.head()

  business_id owner_id   business_type environment_type
0        B001     O001  Small Producer            Rural
1        B002     O002     Retail Shop       Peri-Urban
2        B003     O003  Small Producer            Urban
3        B004     O004     Food Vendor       Semi-Urban
4        B005     O005     Food Vendor            Urban

In [11]:
locations = [
    "Delhi",
    "Mumbai",
    "Jaipur",
    "Lucknow",
    "Indore",
    "Kochi",
    "Guwahati",
    "Bengaluru",
    "Ahmedabad",
    "Patna"
]

business_df["location"] = np.random.choice(
    locations,
    size=len(business_df)
)

business_df.head()

  business_id owner_id   business_type environment_type location
0        B001     O001  Small Producer            Rural    Patna
1        B002     O002     Retail Shop       Peri-Urban    Kochi
2        B003     O003  Small Producer            Urban  Lucknow
3        B004     O004     Food Vendor       Semi-Urban   Jaipur
4        B005     O005     Food Vendor            Urban  Lucknow

In [12]:
months = pd.date_range(
    start="2024-01-01",
    periods=24,
    freq="MS"
)

months

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01',
               '2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01',
               '2025-09-01', '2025-10-01', '2025-11-01', '2025-12-01'],
              dtype='datetime64[us]', freq='MS')

In [13]:
monthly_df = business_df.merge(
    pd.DataFrame({"month": months}),
    how="cross"
)

monthly_df.shape

(12000, 6)

In [14]:
base_income = {
    "Retail Shop": 45000,
    "Food Vendor": 30000,
    "Transport Worker": 28000,
    "Artisan": 32000,
    "Freelancer": 40000,
    "Small Producer": 35000,
    "Home Business": 25000,
    "Micro Service Business": 30000
}

In [15]:
expense_ratio = {
    "Retail Shop": 0.72,
    "Food Vendor": 0.65,
    "Transport Worker": 0.55,
    "Artisan": 0.60,
    "Freelancer": 0.40,
    "Small Producer": 0.68,
    "Home Business": 0.50,
    "Micro Service Business": 0.55
}

In [16]:
income_variation = np.random.normal(
    loc=1.0,
    scale=0.10,
    size=len(monthly_df)
)
monthly_df["monthly_income"] = (
    monthly_df["business_type"]
    .map(base_income)
    * income_variation
).round(2)
monthly_df["monthly_income"].head()

0    28232.13
1    30774.11
2    31252.98
3    37389.18
4    34419.97
Name: monthly_income, dtype: float64

In [17]:
expense_variation = np.random.normal(
    loc=1.0,
    scale=0.05,
    size=len(monthly_df)
)
monthly_df["monthly_expenses"] = (
    monthly_df["monthly_income"]
    * monthly_df["business_type"].map(expense_ratio)
    * expense_variation
).round(2)
monthly_df["monthly_expenses"].head()

0    20097.60
1    19325.85
2    20911.70
3    23891.42
4    20059.14
Name: monthly_expenses, dtype: float64

In [18]:
monthly_df["transaction_count"] = np.maximum(
    1,
    np.round(
        monthly_df["monthly_income"] / 500
        + np.random.normal(0, 8, len(monthly_df))
    )
).astype(int)

monthly_df["transaction_count"].head()

0    61
1    61
2    77
3    55
4    74
Name: transaction_count, dtype: int64

In [19]:
digital_payment_base = {
    "Retail Shop": 65,
    "Food Vendor": 45,
    "Transport Worker": 50,
    "Artisan": 40,
    "Freelancer": 85,
    "Small Producer": 35,
    "Home Business": 55,
    "Micro Service Business": 60
}

digital_payment_variation = np.random.normal(
    loc=0,
    scale=8,
    size=len(monthly_df)
)

monthly_df["digital_payment_pct"] = (
    monthly_df["business_type"].map(digital_payment_base)
    + digital_payment_variation
).clip(0, 100).round(2)

monthly_df["digital_payment_pct"].head()

0    36.62
1    23.46
2    43.26
3    46.95
4    36.71
Name: digital_payment_pct, dtype: float64

In [20]:
supplier_payment_ratio = {
    "Retail Shop": 0.45,
    "Food Vendor": 0.35,
    "Transport Worker": 0.15,
    "Artisan": 0.30,
    "Freelancer": 0.10,
    "Small Producer": 0.40,
    "Home Business": 0.25,
    "Micro Service Business": 0.20
}

supplier_payment_variation = np.random.normal(
    loc=1.0,
    scale=0.08,
    size=len(monthly_df)
)

monthly_df["supplier_payment_amount"] = (
    monthly_df["monthly_expenses"]
    * monthly_df["business_type"].map(supplier_payment_ratio)
    * supplier_payment_variation
).clip(lower=0).round(2)

monthly_df["supplier_payment_amount"].head()

0    6822.95
1    7602.88
2    8474.66
3    9008.03
4    8257.39
Name: supplier_payment_amount, dtype: float64

In [21]:
utility_ratio = {
    "Retail Shop": 0.08,
    "Food Vendor": 0.07,
    "Transport Worker": 0.04,
    "Artisan": 0.06,
    "Freelancer": 0.03,
    "Small Producer": 0.08,
    "Home Business": 0.05,
    "Micro Service Business": 0.05
}

utility_variation = np.random.normal(
    loc=1.0,
    scale=0.10,
    size=len(monthly_df)
)

monthly_df["utility_payment_amount"] = (
    monthly_df["monthly_expenses"]
    * monthly_df["business_type"].map(utility_ratio)
    * utility_variation
).clip(lower=0).round(2)

monthly_df["utility_payment_amount"].head()

0    1740.41
1    1513.32
2    1742.62
3    2039.76
4    1517.20
Name: utility_payment_amount, dtype: float64

In [22]:
rent_base = {
    "Urban": 9000,
    "Semi-Urban": 6500,
    "Rural": 4000,
    "Peri-Urban": 5500
}

rent_variation = np.random.normal(
    loc=1.0,
    scale=0.08,
    size=len(monthly_df)
)

monthly_df["rent_payment"] = (
    monthly_df["environment_type"].map(rent_base)
    * rent_variation
).clip(lower=0).round(2)

monthly_df["rent_payment"].head()

0    3533.82
1    4819.54
2    4142.26
3    4523.88
4    4261.72
Name: rent_payment, dtype: float64

In [23]:
cash_before_savings = (
    monthly_df["monthly_income"]
    - monthly_df["monthly_expenses"]
    - monthly_df["rent_payment"]
)

savings_rate = np.random.uniform(
    0.05,
    0.25,
    size=len(monthly_df)
)

monthly_df["savings_amount"] = (
    cash_before_savings * savings_rate
).clip(lower=0).round(2)

monthly_df["savings_amount"].head()

0     399.91
1     961.85
2     852.05
3    1191.78
4    1406.07
Name: savings_amount, dtype: float64

In [24]:
monthly_df["net_cash_flow"] = (
    monthly_df["monthly_income"]
    - monthly_df["monthly_expenses"]
    - monthly_df["rent_payment"]
    - monthly_df["utility_payment_amount"]
).round(2)

monthly_df["net_cash_flow"].head()

0    2860.30
1    5115.40
2    4456.40
3    6934.12
4    8581.91
Name: net_cash_flow, dtype: float64

In [25]:
payment_discipline_base = {
    "Retail Shop": 82,
    "Food Vendor": 78,
    "Transport Worker": 75,
    "Artisan": 80,
    "Freelancer": 85,
    "Small Producer": 76,
    "Home Business": 81,
    "Micro Service Business": 83
}

payment_discipline_variation = np.random.normal(
    loc=0,
    scale=7,
    size=len(monthly_df)
)

monthly_df["payment_discipline_pct"] = (
    monthly_df["business_type"].map(payment_discipline_base)
    + payment_discipline_variation
).clip(0, 100).round(2)

monthly_df["payment_discipline_pct"].head()

0    70.84
1    70.99
2    75.25
3    81.06
4    74.54
Name: payment_discipline_pct, dtype: float64

In [26]:
supplier_reliability_base = {
    "Retail Shop": 78,
    "Food Vendor": 75,
    "Transport Worker": 72,
    "Artisan": 76,
    "Freelancer": 82,
    "Small Producer": 74,
    "Home Business": 77,
    "Micro Service Business": 80
}

supplier_reliability_variation = np.random.normal(
    loc=0,
    scale=8,
    size=len(monthly_df)
)

monthly_df["supplier_reliability_pct"] = (
    monthly_df["business_type"].map(supplier_reliability_base)
    + supplier_reliability_variation
).clip(0, 100).round(2)

monthly_df["supplier_reliability_pct"].head()

0    77.22
1    89.33
2    71.17
3    82.35
4    78.87
Name: supplier_reliability_pct, dtype: float64

In [27]:
continuity_base = {
    "Retail Shop": 88,
    "Food Vendor": 82,
    "Transport Worker": 80,
    "Artisan": 84,
    "Freelancer": 90,
    "Small Producer": 78,
    "Home Business": 86,
    "Micro Service Business": 88
}

continuity_variation = np.random.normal(
    loc=0,
    scale=6,
    size=len(monthly_df)
)

monthly_df["business_continuity_pct"] = (
    monthly_df["business_type"].map(continuity_base)
    + continuity_variation
).clip(0, 100).round(2)

monthly_df["business_continuity_pct"].head()

0    77.39
1    83.80
2    76.42
3    79.07
4    77.85
Name: business_continuity_pct, dtype: float64

In [28]:
demand_stability_base = {
    "Retail Shop": 78,
    "Food Vendor": 72,
    "Transport Worker": 68,
    "Artisan": 70,
    "Freelancer": 80,
    "Small Producer": 74,
    "Home Business": 73,
    "Micro Service Business": 79
}

demand_stability_variation = np.random.normal(
    loc=0,
    scale=8,
    size=len(monthly_df)
)

monthly_df["demand_stability_pct"] = (
    monthly_df["business_type"].map(demand_stability_base)
    + demand_stability_variation
).clip(0, 100).round(2)

monthly_df["demand_stability_pct"].head()

0    73.27
1    76.29
2    67.41
3    73.02
4    76.99
Name: demand_stability_pct, dtype: float64

In [29]:
seasonal_factors = {
    1: 0.95,
    2: 0.97,
    3: 1.00,
    4: 1.02,
    5: 1.05,
    6: 1.08,
    7: 1.03,
    8: 1.00,
    9: 0.98,
    10: 1.10,
    11: 1.15,
    12: 1.20
}

monthly_df["seasonal_factor"] = monthly_df["month"].dt.month.map(
    seasonal_factors
)

monthly_df[["month", "seasonal_factor"]].head(15)

        month  seasonal_factor
0  2024-01-01             0.95
1  2024-02-01             0.97
2  2024-03-01             1.00
3  2024-04-01             1.02
4  2024-05-01             1.05
5  2024-06-01             1.08
6  2024-07-01             1.03
7  2024-08-01             1.00
8  2024-09-01             0.98
9  2024-10-01             1.10
10 2024-11-01             1.15
11 2024-12-01             1.20
12 2025-01-01             0.95
13 2025-02-01             0.97
14 2025-03-01             1.00

In [30]:
monthly_df["seasonally_adjusted_income"] = (
    monthly_df["monthly_income"]
    * monthly_df["seasonal_factor"]
).round(2)

monthly_df[[
    "month",
    "monthly_income",
    "seasonal_factor",
    "seasonally_adjusted_income"
]].head(12)

        month  monthly_income  seasonal_factor  seasonally_adjusted_income
0  2024-01-01        28232.13             0.95                    26820.52
1  2024-02-01        30774.11             0.97                    29850.89
2  2024-03-01        31252.98             1.00                    31252.98
3  2024-04-01        37389.18             1.02                    38136.96
4  2024-05-01        34419.97             1.05                    36140.97
5  2024-06-01        32110.45             1.08                    34679.29
6  2024-07-01        43084.03             1.03                    44376.55
7  2024-08-01        32676.36             1.00                    32676.36
8  2024-09-01        39084.86             0.98                    38303.16
9  2024-10-01        40673.88             1.10                    44741.27
10 2024-11-01        29505.14             1.15                    33930.91
11 2024-12-01        35258.87             1.20                    42310.64

In [31]:
shock_types = [
    "None",
    "Demand Drop",
    "Supply Disruption",
    "Operating Cost Increase"
]

shock_probabilities = [0.82, 0.07, 0.06, 0.05]

monthly_df["shock_type"] = np.random.choice(
    shock_types,
    size=len(monthly_df),
    p=shock_probabilities
)

shock_factor_map = {
    "None": 1.00,
    "Demand Drop": 0.75,
    "Supply Disruption": 0.85,
    "Operating Cost Increase": 0.90
}

monthly_df["shock_factor"] = monthly_df["shock_type"].map(
    shock_factor_map
)

monthly_df["shock_type"].value_counts()

shock_type
None                       9818
Demand Drop                 828
Supply Disruption           713
Operating Cost Increase     641
Name: count, dtype: int64

In [32]:
monthly_df["adjusted_income"] = (
    monthly_df["seasonally_adjusted_income"]
    * monthly_df["shock_factor"]
).round(2)

monthly_df["adjusted_expenses"] = (
    monthly_df["monthly_expenses"]
    * np.where(
        monthly_df["shock_type"].eq("Operating Cost Increase"),
        1.20,
        np.where(
            monthly_df["shock_type"].eq("Supply Disruption"),
            1.10,
            1.00
        )
    )
).round(2)

monthly_df["adjusted_cash_flow"] = (
    monthly_df["adjusted_income"]
    - monthly_df["adjusted_expenses"]
    - monthly_df["rent_payment"]
    - monthly_df["utility_payment_amount"]
).round(2)

monthly_df[
    [
        "shock_type",
        "adjusted_income",
        "adjusted_expenses",
        "adjusted_cash_flow"
    ]
].head(10)

  shock_type  adjusted_income  adjusted_expenses  adjusted_cash_flow
0       None         26820.52           20097.60             1448.69
1       None         29850.89           19325.85             4192.18
2       None         31252.98           20911.70             4456.40
3       None         38136.96           23891.42             7681.90
4       None         36140.97           20059.14            10302.91
5       None         34679.29           20492.95             8211.25
6       None         44376.55           29451.59             8536.56
7       None         32676.36           22864.66             3440.44
8       None         38303.16           26147.89             6085.22
9       None         44741.27           29558.53             8577.74

In [33]:
# Cash-flow stability
monthly_df["cash_flow_margin_pct"] = (
    monthly_df["adjusted_cash_flow"]
    / monthly_df["adjusted_income"].replace(0, np.nan)
    * 100
).clip(-100, 100).fillna(0).round(2)

# Financial pressure
monthly_df["expense_burden_pct"] = (
    monthly_df["adjusted_expenses"]
    / monthly_df["adjusted_income"].replace(0, np.nan)
    * 100
).clip(0, 200).fillna(0).round(2)

# Overall operational stability
monthly_df["operational_stability_pct"] = (
    monthly_df[
        [
            "payment_discipline_pct",
            "supplier_reliability_pct",
            "business_continuity_pct",
            "demand_stability_pct"
        ]
    ].mean(axis=1)
).round(2)

# Financial health
monthly_df["financial_health_pct"] = (
    monthly_df["cash_flow_margin_pct"].clip(0, 100) * 0.45
    + (100 - monthly_df["expense_burden_pct"].clip(0, 100)) * 0.30
    + monthly_df["payment_discipline_pct"] * 0.25
).clip(0, 100).round(2)

# Resilience
monthly_df["resilience_pct"] = (
    monthly_df[
        [
            "business_continuity_pct",
            "demand_stability_pct",
            "supplier_reliability_pct"
        ]
    ].mean(axis=1)
).round(2)

monthly_df[
    [
        "cash_flow_margin_pct",
        "expense_burden_pct",
        "operational_stability_pct",
        "financial_health_pct",
        "resilience_pct"
    ]
].head()

,cash_flow_margin_pct,expense_burden_pct,operational_stability_pct,financial_health_pct,resilience_pct
0,5.40,74.93,74.68,27.66,75.96
1,14.04,64.74,80.10,34.64,83.14
2,14.26,66.91,72.56,35.16,71.67
3,20.14,62.65,78.88,40.53,78.15
4,28.51,55.50,77.06,44.81,77.90

In [34]:
monthly_df["economic_reputation_index"] = (
    monthly_df["financial_health_pct"] * 0.35
    + monthly_df["operational_stability_pct"] * 0.25
    + monthly_df["resilience_pct"] * 0.20
    + monthly_df["payment_discipline_pct"] * 0.20
).clip(0, 100).round(2)

monthly_df[
    [
        "business_id",
        "month",
        "financial_health_pct",
        "operational_stability_pct",
        "resilience_pct",
        "economic_reputation_index"
    ]
].head()

,business_id,month,financial_health_pct,operational_stability_pct,resilience_pct,economic_reputation_index
0,B001,2024-01-01,27.66,74.68,75.96,57.71
1,B001,2024-02-01,34.64,80.10,83.14,62.98
2,B001,2024-03-01,35.16,72.56,71.67,59.83
3,B001,2024-04-01,40.53,78.88,78.15,65.75
4,B001,2024-05-01,44.81,77.06,77.90,65.44

In [35]:
print("Dataset shape:", monthly_df.shape)
print("Duplicate rows:", monthly_df.duplicated().sum())
print("Missing values:", monthly_df.isna().sum().sum())
print("Unique businesses:", monthly_df["business_id"].nunique())
print("Unique months:", monthly_df["month"].nunique())

print("\nBusiness type distribution:")
print(monthly_df["business_type"].value_counts())

print("\nShock distribution:")
print(monthly_df["shock_type"].value_counts())

print("\nReputation statistics:")
print(monthly_df["economic_reputation_index"].describe())

Dataset shape: (12000, 32)
Duplicate rows: 0
Missing values: 0
Unique businesses: 500
Unique months: 24

Business type distribution:
business_type
Retail Shop               2400
Food Vendor               1920
Small Producer            1440
Transport Worker          1440
Micro Service Business    1200
Home Business             1200
Freelancer                1200
Artisan                   1200
Name: count, dtype: int64

Shock distribution:
shock_type
None                       9818
Demand Drop                 828
Supply Disruption           713
Operating Cost Increase     641
Name: count, dtype: int64

Reputation statistics:
count    12000.000000
mean        65.032995
std          5.603023
min         48.920000
25%         61.060000
50%         64.500000
75%         68.360000
max         85.870000
Name: economic_reputation_index, dtype: float64

In [36]:
monthly_df.to_csv(
    "../data/trustmesh_economic_data.csv",
    index=False
)

print("Dataset saved successfully.")

Dataset saved successfully.

In [37]:
monthly_df.columns.tolist()

['business_id',
 'owner_id',
 'business_type',
 'environment_type',
 'location',
 'month',
 'monthly_income',
 'monthly_expenses',
 'transaction_count',
 'digital_payment_pct',
 'supplier_payment_amount',
 'utility_payment_amount',
 'rent_payment',
 'savings_amount',
 'net_cash_flow',
 'payment_discipline_pct',
 'supplier_reliability_pct',
 'business_continuity_pct',
 'demand_stability_pct',
 'seasonal_factor',
 'seasonally_adjusted_income',
 'shock_type',
 'shock_factor',
 'adjusted_income',
 'adjusted_expenses',
 'adjusted_cash_flow',
 'cash_flow_margin_pct',
 'expense_burden_pct',
 'operational_stability_pct',
 'financial_health_pct',
 'resilience_pct',
 'economic_reputation_index']

In [38]:
data_dictionary = {
    "business_id": ("string", "Unique identifier assigned to each business.", "Identity"),
    "owner_id": ("string", "Unique identifier assigned to each business owner.", "Identity"),
    "business_type": ("string", "Type of informal business.", "Identity"),
    "environment_type": ("string", "Operating environment of the business.", "Context"),
    "location": ("string", "Geographic location assigned to the business.", "Context"),
    "month": ("datetime", "Monthly observation period.", "Time"),

    "monthly_income": ("float", "Simulated monthly business income before seasonal and shock adjustments.", "Financial"),
    "monthly_expenses": ("float", "Simulated monthly operating expenses.", "Financial"),
    "transaction_count": ("integer", "Approximate number of monthly business transactions.", "Financial"),
    "digital_payment_pct": ("float", "Estimated percentage of transactions conducted digitally.", "Financial"),
    "supplier_payment_amount": ("float", "Estimated monthly amount paid to suppliers.", "Financial"),
    "utility_payment_amount": ("float", "Estimated monthly utility payments.", "Financial"),
    "rent_payment": ("float", "Estimated monthly business-related rent payment.", "Financial"),
    "savings_amount": ("float", "Estimated monthly savings based on available cash.", "Financial"),
    "net_cash_flow": ("float", "Monthly income remaining after core expenses, rent, and utilities.", "Financial"),

    "payment_discipline_pct": ("float", "Estimated consistency of making expected payments on time.", "Behavioral"),
    "supplier_reliability_pct": ("float", "Estimated reliability of the business in supplier-related activity.", "Behavioral"),
    "business_continuity_pct": ("float", "Estimated consistency of business operations over time.", "Behavioral"),
    "demand_stability_pct": ("float", "Estimated stability of customer demand.", "Behavioral"),

    "seasonal_factor": ("float", "Monthly seasonal multiplier applied to income.", "Temporal"),
    "seasonally_adjusted_income": ("float", "Income adjusted according to the seasonal factor.", "Derived"),

    "shock_type": ("string", "Economic condition affecting the monthly observation.", "Shock"),
    "shock_factor": ("float", "Multiplier representing the effect of the economic shock.", "Shock"),
    "adjusted_income": ("float", "Income after applying seasonal and shock effects.", "Derived"),
    "adjusted_expenses": ("float", "Expenses after applying relevant operating-cost shock effects.", "Derived"),
    "adjusted_cash_flow": ("float", "Cash flow after adjusted income, expenses, rent, and utilities.", "Derived"),

    "cash_flow_margin_pct": ("float", "Adjusted cash flow expressed as a percentage of adjusted income.", "Derived"),
    "expense_burden_pct": ("float", "Adjusted expenses expressed as a percentage of adjusted income.", "Derived"),
    "operational_stability_pct": ("float", "Composite indicator based on payment discipline, supplier reliability, continuity, and demand stability.", "Reputation"),
    "financial_health_pct": ("float", "Composite indicator representing financial health using cash flow, expense burden, and payment discipline.", "Reputation"),
    "resilience_pct": ("float", "Composite indicator representing operational and economic resilience.", "Reputation"),
    "economic_reputation_index": ("float", "Explainable composite index combining financial health, operational stability, resilience, and payment discipline.", "Reputation")
}

with open("../docs/data_dictionary.md", "w", encoding="utf-8") as f:
    f.write("# TrustMesh AI — Data Dictionary\n\n")
    f.write("This document describes the fields contained in the synthetic TrustMesh AI economic dataset.\n\n")
    f.write(f"**Dataset:** `trustmesh_economic_data.csv`  \n")
    f.write(f"**Rows:** {len(monthly_df):,}  \n")
    f.write(f"**Columns:** {len(monthly_df.columns)}  \n\n")

    f.write("| Column | Data Type | Description | Category |\n")
    f.write("|---|---|---|---|\n")

    for column in monthly_df.columns:
        dtype, description, category = data_dictionary[column]
        f.write(f"| `{column}` | {dtype} | {description} | {category} |\n")

print("Data dictionary created successfully.")

Data dictionary created successfully.

In [39]:
monthly_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   business_id                 12000 non-null  str
 1   owner_id                    12000 non-null  str
 2   business_type               12000 non-null  str
 3   environment_type            12000 non-null  str
 4   location                    12000 non-null  str
 5   month                       12000 non-null  datetime64[us]
 6   monthly_income              12000 non-null  float64
 7   monthly_expenses            12000 non-null  float64
 8   transaction_count           12000 non-null  int64
 9   digital_payment_pct         12000 non-null  float64
 10  supplier_payment_amount     12000 non-null  float64
 11  utility_payment_amount      12000 non-null  float64
 12  rent_payment                12000 non-null  float64
 13  savings_amount              12000 non-null  float64
 14  net_cash_flow               12000 non-null  float64
 15  payment_discipline_pct      12000 non-null  float64
 16  supplier_reliability_pct    12000 non-null  float64
 17  business_continuity_pct     12000 non-null  float64
 18  demand_stability_pct        12000 non-null  float64
 19  seasonal_factor             12000 non-null  float64
 20  seasonally_adjusted_income  12000 non-null  float64
 21  shock_type                  12000 non-null  str
 22  shock_factor                12000 non-null  float64
 23  adjusted_income             12000 non-null  float64
 24  adjusted_expenses           12000 non-null  float64
 25  adjusted_cash_flow          12000 non-null  float64
 26  cash_flow_margin_pct        12000 non-null  float64
 27  expense_burden_pct          12000 non-null  float64
 28  operational_stability_pct   12000 non-null  float64
 29  financial_health_pct        12000 non-null  float64
 30  resilience_pct              12000 non-null  float64
 31  economic_reputation_index   12000 non-null  float64
dtypes: datetime64[us](1), float64(24), int64(1), str(6)
memory usage: 3.4 MB